name: Terraform Apply for Azure PostgreSQL

on:
  push:
    branches:
      - test-branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: PostgreSQL_Flexible_Server

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve
